if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0131629"
    echo -en "\x1b]P1d4615d"
    echo -en "\x1b]P2c5c95e"
    echo -en "\x1b]P38861e5"
    echo -en "\x1b]P4f286bc"
    echo -en "\x1b]P55692e5"
    echo -en "\x1b]P684c9e0"
    echo -en "\x1b]P7c7cbe4"
    echo -en "\x1b]P8202545"
    echo -en "\x1b]P9de8986"
    echo -en "\x1b]PAd3d684"
    echo -en "\x1b]PBa98cec"
    echo -en "\x1b]PCf7b5d6"
    echo -en "\x1b]PD82aeec"
    echo -en "\x1b]PEaddbea"
    echo -en "\x1b]PFe3e5f1"
    clear
fi
