if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0{{base}}"
    echo -en "\x1b]P1{{whoswho}}"
    echo -en "\x1b]P2{{sasaki}}"
    echo -en "\x1b]P3{{pageone}}"
    echo -en "\x1b]P4{{ulti}}"
    echo -en "\x1b]P5{{drake}}"
    echo -en "\x1b]P6{{blackmaria}}"
    echo -en "\x1b]P7{{text}}"
    echo -en "\x1b]P8{{overlay}}"
    echo -en "\x1b]P9{{sabretooth}}"
    echo -en "\x1b]PA{{triceratops}}"
    echo -en "\x1b]PB{{spinosaurus}}"
    echo -en "\x1b]PC{{pachycephalos}}"
    echo -en "\x1b]PD{{allosaurus}}"
    echo -en "\x1b]PE{{rosamygale}}"
    echo -en "\x1b]PF{{light}}"
    clear
fi
